import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/composantes/Acceuille/Header";
import Footer from "@/composantes/Acceuille/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className={`${geistMono.variable} h-full`}>
      <body className="flex flex-col min-h-screen bg-white text-slate-800 antialiased [--pad:clamp(1rem,3vw,2rem)]">
        {/* Fond décoratif */}
        <div className="pointer-events-none fixed inset-0 -z-10 bg-glow"></div>



        {/* Contenu principal qui prend tout l’espace restant */}
        <main className="flex-1">{children}</main>


      </body>
    </html>
  );
}
